name: Manual Deploy to Oracle VM

on:
  workflow_dispatch: # run manually from GitHub Actions tab

env:
  appName: 'tarotapp.service'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    # 1. Checkout repo
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Setup .NET 8
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    # 3. Publish app for Linux
    - name: Publish app
      run: |
        cd TarotService
        dotnet publish -c Release -r linux-x64 --self-contained false -o publish

    # 4. Copy files to VM via SCP
    - name: Copy files to Oracle VM
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.TAROTSERVICE_APP_VM_HOST }}
        username: ${{ secrets.TAROTSERVICE_APP_VM_USER }}
        key: ${{ secrets.TAROTSERVICE_APP_VM_SSH_KEY }}
        source: "publish/*"
        target: "${{ secrets.TAROTSERVICE_APP_VM_PATH }}"
        overwrite: true

    # 5. Restart systemd service
    - name: Restart app on VM
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.TAROTSERVICE_APP_VM_HOST }}
        username: ${{ secrets.TAROTSERVICE_APP_VM_USER }}
        key: ${{ secrets.TAROTSERVICE_APP_VM_SSH_KEY }}
        script: |
          sudo systemctl restart ${{ env.acrName }}
          sudo systemctl status ${{ env.acrName }} --no-pager
